### ISSUE TITLE
add to hassio

### ISSUE THREAD

**Issue by djmalin** [fineemb/Xiaomi-Smart-Multipurpose-Kettle#1]
Hello @fineemb , you can help with this integration, all I was able to get is only the data in the picture, and how to turn it on using hassio?
![czajnik](https://user-images.githubusercontent.com/57156960/77233733-c3645900-6ba9-11ea-95c4-066b6f7f4b8c.jpg)

**Comment by GenoMXXX** [comment]
You should creatre scripts, like in description. For example:

```
boiled_water:
  sequence:
    service: health_pot.set_work
    data:
      entity_id: health_pot.xiaomi_40313cca037b
      status: 2
      id: 18
      keep_temp: 95
      keep_time: 1
```

**Comment by maximatchev** [comment]
Hi @fineemb 
I can't stop boiling by script

```
stop_work:
  sequence:
    service: health_pot.set_work
    data:
      entity_id: health_pot.xiaomi_40313ce00458
      status: 5
      id: 18

```

It doesn't work ((
